## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Iqaluit,CA,63.7506,-68.5145,15.53,92,90,3.44,overcast clouds
1,1,Busselton,AU,-33.6500,115.3333,77.04,47,2,9.53,clear sky
2,2,Porto Novo,BJ,6.4965,2.6036,85.82,73,23,9.28,few clouds
3,3,Bundaberg,AU,-24.8500,152.3500,72.21,93,41,4.00,scattered clouds
4,4,Valky,UA,49.8387,35.6207,13.86,98,31,4.92,scattered clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 50
What is the maximum temperature you would like for your trip? 75

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
pref_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
pref_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
3,3,Bundaberg,AU,-24.8500,152.3500,72.21,93,41,4.00,scattered clouds
5,5,Flinders,AU,-34.5833,150.8552,61.21,82,98,4.00,overcast clouds
7,7,Kiunga,PG,-6.1219,141.2906,74.32,100,96,1.52,overcast clouds
10,10,Kodiak,US,57.7900,-152.4072,53.11,50,1,8.05,clear sky
13,13,Taltal,CL,-25.4000,-70.4833,70.39,72,11,6.15,few clouds
15,15,Kapaa,US,22.0752,-159.3190,73.72,76,20,1.99,light rain
25,25,Port Alfred,ZA,-33.5906,26.8910,64.83,93,100,16.55,heavy intensity rain
26,26,Estepona,ES,36.4276,-5.1459,67.91,88,14,6.53,few clouds
35,35,Guhagar,IN,17.4842,73.1929,72.32,69,8,4.94,clear sky
36,36,Mar Del Plata,AR,-38.0023,-57.5575,73.42,82,0,14.00,clear sky

In [5]:
# 4a. Determine if there are any empty rows.
pref_cities_df.count()

City_ID                212
City                   212
Country                208
Lat                    212
Lng                    212
Max Temp               212
Humidity               212
Cloudiness             212
Wind Speed             212
Current Description    212
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = pref_cities_df
clean_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
3,3,Bundaberg,AU,-24.8500,152.3500,72.21,93,41,4.00,scattered clouds
5,5,Flinders,AU,-34.5833,150.8552,61.21,82,98,4.00,overcast clouds
7,7,Kiunga,PG,-6.1219,141.2906,74.32,100,96,1.52,overcast clouds
10,10,Kodiak,US,57.7900,-152.4072,53.11,50,1,8.05,clear sky
13,13,Taltal,CL,-25.4000,-70.4833,70.39,72,11,6.15,few clouds
...,...,...,...,...,...,...,...,...,...,...
719,719,Plouzane,FR,48.3833,-4.6167,55.49,97,75,6.91,moderate rain
721,721,Asilah,MA,35.4650,-6.0348,67.86,87,3,6.87,clear sky
724,724,Broken Hill,AU,-31.9500,141.4333,65.91,26,0,12.66,clear sky
726,726,Coihaique,CL,-45.5752,-72.0662,66.81,26,6,12.08,clear sky
727,727,Vila Franca Do Campo,PT,37.7167,-25.4333,68.20,88,73,21.90,broken clouds

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,Bundaberg,AU,72.21,scattered clouds,-24.8500,152.3500,
5,Flinders,AU,61.21,overcast clouds,-34.5833,150.8552,
7,Kiunga,PG,74.32,overcast clouds,-6.1219,141.2906,
10,Kodiak,US,53.11,clear sky,57.7900,-152.4072,
13,Taltal,CL,70.39,few clouds,-25.4000,-70.4833,
...,...,...,...,...,...,...,...
719,Plouzane,FR,55.49,moderate rain,48.3833,-4.6167,
721,Asilah,MA,67.86,clear sky,35.4650,-6.0348,
724,Broken Hill,AU,65.91,clear sky,-31.9500,141.4333,
726,Coihaique,CL,66.81,clear sky,-45.5752,-72.0662,
727,Vila Franca Do Campo,PT,68.20,broken clouds,37.7167,-25.4333,

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():

    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat}, {lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found..... skipping.")

Hotel not found..... skipping.
Hotel not found..... skipping.
Hotel not found..... skipping.
Hotel not found..... skipping.
Hotel not found..... skipping.
Hotel not found..... skipping.
Hotel not found..... skipping.
Hotel not found..... skipping.
Hotel not found..... skipping.

In [9]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df['Hotel Name'].replace('', inplace=True)
hotel_df.dropna(subset=['Hotel Name'], inplace=True)
clean_hotel_df = hotel_df
clean_hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,Bundaberg,AU,72.21,scattered clouds,-24.8500,152.3500,Takalvan Motel
5,Flinders,AU,61.21,overcast clouds,-34.5833,150.8552,Shellharbour Resort & Conference Centre
7,Kiunga,PG,74.32,overcast clouds,-6.1219,141.2906,Airport Lodge Kiunga
10,Kodiak,US,53.11,clear sky,57.7900,-152.4072,Best Western Kodiak Inn And Convention Center
13,Taltal,CL,70.39,few clouds,-25.4000,-70.4833,Residencial Karime
...,...,...,...,...,...,...,...
719,Plouzane,FR,55.49,moderate rain,48.3833,-4.6167,Lymina
721,Asilah,MA,67.86,clear sky,35.4650,-6.0348,Hotel Zelis
724,Broken Hill,AU,65.91,clear sky,-31.9500,141.4333,Royal Exchange Hotel
726,Coihaique,CL,66.81,clear sky,-45.5752,-72.0662,Diego De Almagro Coyhaique
727,Vila Franca Do Campo,PT,68.20,broken clouds,37.7167,-25.4333,Pestana Bahia Praia

In [10]:
# 8a. Create the output File (CSV)
output_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_file, index_label="City_ID")

In [11]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description}  and  {Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [12]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [13]:
# 11a. Add a marker layer for each city to the map. 
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))